### ISSUE TITLE
Support real framework bundles

### ISSUE THREAD

**Issue by adib** [bitstadium/HockeySDK-tvOS#13]
Is it possible to build HockeySDK as a real `.framework` bundle on tvOS? Namely for installation from Cocoapods.

Currently the default pod spec for HockeySDK-tvOS 4.1.1 seems to build as an embedded framework. This causes *duplicate symbols* warnings at runtime because it gets linked to my own framework and the main application binary. I need my own framework to share code between the main application and the top shelf extension.

**Comment by ElektrojungeAtWork** [comment]
Hey Sasmito,

thanks for getting in touch.
We currently have no plans to switch to a "real" `framework` for our SDK. That said, you are the first person to report problems with this and I'd love to help.
Could you post the warnings here, so that I can take a look at them?

Best,
Benjamin

**Comment by adib** [comment]
Hi Benjamin,

The following is an excerpt of the warnings that I got during the app's startup

	Class BITCrashMetaData is implemented in both /Users/adib/Library/Developer/Xcode/DerivedData/WakeUp-fbiegguasydmdwdaoedddfmjtjlh/Build/Products/Debug-appletvsimulator/tvCommon.framework/tvCommon (0x102664850) and /Users/adib/Library/Developer/CoreSimulator/Devices/5A7A7225-E2F6-474F-8C52-78A55BF194A6/data/Containers/Bundle/Application/8F1EDC18-F68B-42F2-851C-87BB99C6432B/WakeUp.app/WakeUp (0x101c19b20). One of the two will be used. Which one is undefined.

**Comment by ghost** [comment]
I think you just need to make sure that HockeySDK is not added to your framework AND your app target but only the framework.

**Comment by adib** [comment]
@anlinde That's a workaround that requires manual editing of the `.xcconfig` files that Cocoapods generate (and re-editing after each `pod update`). Even if HockeySDK is only added as a dependency of a framework, by default for Swift projects (in which `use_frameworks!` is applied) it gets linked to the main binary. Furthermore I couldn't test whether HockeySDK was able to find its resources correctly in this setup (which, IMO, would be solvable if it's already configured and tested as a `.framework` upstream).

**Comment by ElektrojungeAtWork** [comment]
@adib I see. Is manual integration of the binaries not an option for you?

**Comment by adib** [comment]
@TroubleMakerBen That's yet another workaround. I'll be creating a `.framework` bundle and some wrapper code just for HockeyApp (which is what I'm doing right now). In other words, I'm doing the `.framework` bundle packaging for you.

**Comment by ElektrojungeAtWork** [comment]
@adib I totally see where you are coming from and understand the reasons you want this.
We're hard at work on [Mobile Center](https://www.hockeyapp.net/mobile-center/about/) right now and limited resources right now (especially as [//build](https://build.microsoft.com/) is this week). This gives you and me three choices:
1. You are okay as is for now, and once we have the Mobile Center SDK for tvOS out there (which I cannot give you an ETA for, unfortunately), you switch over to it.
2. You fix this and create a PR for it, which I'll happily merge.
3. You are okay with this for now and we change this in tvOS, which, to be honest, I cannot promise any timeline for.

I hope you understand that we have limited resources right now. I care about your feedback a lot, feel free to get with me directly [in our public slack](hockeycamp.slack.com), via [support](https://support.hockeyapp.net) or directly via email to bereimol AT my employer's name DOT com.

Benny
