### ISSUE TITLE
Crash report is saved to cache directory. Will that be purged?

### ISSUE THREAD

**Issue by haol1u** [bitstadium/HockeySDK-tvOS#6]
Since tvOS has very strict limitation over local storage. 500k for NSUserDefaults. And all files stored in cache directory will be purge when system resource is running low or device is rebooted.

Have you considered about this case?

Thanks!
Hao

**Comment by lumaxis** [comment]
Yes, we considered this case. There is unfortunately no other way for us to save data than in the Caches directory. We can't clutter the NSUserDefaults with potentially big crash reports and using iCloud storage for this would most likely result in an App Store review rejection.

**Comment by haol1u** [comment]
@lumaxis Thanks a lot! That's a great answer. Maybe they should be rethinking this kind limitation.
